# Generated by Django 4.2.5 on 2023-10-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_url',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
